name: dietapp
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  google_nav_bar: ^5.0.6
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  line_awesome_flutter: ^2.0.0
  image_picker: ^0.8.4+11
  provider:
  ionicons: ^0.2.1
  audioplayers: ^0.20.1
  #error snackbar
  awesome_snackbar_content: ^0.1.0
  flutter_svg: ^1.0.3

  #Tensorflow Lite
  tflite:
    path: ./lib/flutter_tflite-master
  get: ^4.6.5

  #Google Maps
  geolocator: ^9.0.2
  google_maps_flutter: 

  #web view
  webview_flutter: ^3.0.2

  #river
  rive: ^0.9.1

  #firebase
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  firebase_core_platform_interface: 4.5.1 # note removed ^
  firebase_messaging: ^13.0.4 # previously I only had this which was pulling in 4.5.2 which you do not want

  #gives error
  #firebase_storage: ^11.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/



  fonts:
  - family: Quicksand
    fonts:
    - asset: assets/fonts/Quicksand-Regular.ttf
  - family: Pacifico
    fonts:
    - asset: assets/fonts/Pacifico-Regular.ttf
  - family: Source Sans Pro
    fonts:
    - asset: assets/fonts/SourceSansPro-Regular.ttf
  - family: Raleway
    fonts:
    - asset: assets/fonts/Raleway-Regular.ttf
