name: dietapp
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  google_nav_bar: ^5.0.6
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  line_awesome_flutter: ^2.0.0
  image_picker: ^0.8.4+11
  provider:
  ionicons: ^0.2.1
  audioplayers: ^0.20.1
  google_sign_in: ^5.4.2
  toast: ^0.3.0
  #error snackbar
  awesome_snackbar_content: ^0.1.0
  flutter_svg: ^1.0.3
  smooth_page_indicator: ^1.0.0

  #QR code
  qr_flutter: ^4.0.0 
  qr_code_scanner: ^1.0.1

  #Tensorflow Lite
  tflite:
    path: ./lib/flutter_tflite-master
  get: ^4.6.5
  get_storage: ^2.0.3

  #Google Maps
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  location: ^4.4.0
  google_maps_flutter: 
  google_maps_place_picker_mb: ^3.0.1 #delete later
  flutter_google_places_sdk: ^0.3.2+6
  custom_info_window: ^1.0.1
  geocoding: ^2.0.5
  #google_maps_controller: ^1.2.0

  #web view
  webview_flutter: ^3.0.2

  #Wearos
  wear: ^1.1.0
  rotary_scrollbar: ^0.1.1
  watch_connectivity: ^0.1.4+1
  watch_connectivity_garmin: ^0.1.2
  #wearable_communicator: ^0.1.1

  #river
  rive: ^0.9.1

  #firebase
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  firebase_core_platform_interface: 4.5.3 # note removed ^
  firebase_messaging: ^14.0.1 # previously I only had this which was pulling in 4.5.2 which you do not want
  open_street_map_search_and_pick: ^0.0.16
  #gives error
  #firebase_storage: ^11.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

dependency_overrides:
  watch_connectivity_platform_interface: ^0.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    



  fonts:
  - family: Quicksand
    fonts:
    - asset: assets/fonts/Quicksand-Regular.ttf
  - family: Pacifico
    fonts:
    - asset: assets/fonts/Pacifico-Regular.ttf
  - family: Source Sans Pro
    fonts:
    - asset: assets/fonts/SourceSansPro-Regular.ttf
  - family: Raleway
    fonts:
    - asset: assets/fonts/Raleway-Regular.ttf
