// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBked4f_LCYYMnfBKS5O48cTXPBRCXwiSY',
    appId: '1:131660603449:web:3c5be20bac2de76e25ade8',
    messagingSenderId: '131660603449',
    projectId: 'dietapp-5db27',
    authDomain: 'dietapp-5db27.firebaseapp.com',
    storageBucket: 'dietapp-5db27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNPJCKnLTUA4Z4Ig0cRXlbXIXxGcUSd_k',
    appId: '1:131660603449:android:62649c0c7c8729a425ade8',
    messagingSenderId: '131660603449',
    projectId: 'dietapp-5db27',
    storageBucket: 'dietapp-5db27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4cyq1eYH-LBqIxQ40qwnZDP-_BzOJsjI',
    appId: '1:131660603449:ios:abf2e294e9e4fa7e25ade8',
    messagingSenderId: '131660603449',
    projectId: 'dietapp-5db27',
    storageBucket: 'dietapp-5db27.appspot.com',
    iosClientId: '131660603449-9930d5643r2v835du8vag62iorug4ogg.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4cyq1eYH-LBqIxQ40qwnZDP-_BzOJsjI',
    appId: '1:131660603449:ios:abf2e294e9e4fa7e25ade8',
    messagingSenderId: '131660603449',
    projectId: 'dietapp-5db27',
    storageBucket: 'dietapp-5db27.appspot.com',
    iosClientId: '131660603449-9930d5643r2v835du8vag62iorug4ogg.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietapp',
  );
}
